### PR TITLE
Replace Information Screen's "Lorem Ipsum" with proper copy

### LINKED ISSUE #166: Update Information screen & remove Lorem ipsum
Simulator Screen Shot - iPhone 5s - 2020-04-04 at 18 12 28

### PR DESCRIPTION
**Pull request by cjmlgrto**
This PR will resolve #166 by replacing the “Lorem Ipsum” copy in the app’s Information Screen with more appropriate copy about the app.

## Changes

Updates the Information Screen (`info_view.dart`) to use the following copy, sourced from the repo's README intro paragraph:

> This app aims to help safeguard the welfare of Western Health anaesthetists working amidst the COVID-19 pandemic by providing the most up-to-date information for time-critical procedures to ensure optimal patient care.

## Screenshots

Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-04 at 21 31 02

### CODE REVIEW

**Comment by workerbee22** [comment]
@cjmlgrto I think we should get Gregg to review/tweak this copy as the business owner, which is what we are doing with all the rest. 

I'm also not convinced this copy even needs to be here. Do we need it? What does it add? By the time the user is in here, they have seen the app and get a feel for what it is. If anything key messages here would be in onboarding screens, but we've de-prioritised that for now.

**Comment by workerbee22** [comment]
Another related issue is here : https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/147

Its related because things like version are super easy to get from some Flutter apis listed in that issue too. 👍

**Comment by cjmlgrto** [comment]
@workerbee22 good point — best to drop the paragraph in the first place then 👍 

Should I close this PR and make a new one that suggests dropping it?

**Comment by workerbee22** [comment]
Lets keep it open and get some more comments Im thinking?

**Comment by kimngyn** [comment]
It looks very nice! I think the hospital staff would rather read this than Lorem Ipsum. I’m not very good with Latin 🤗

**Comment by greggmiller** [comment]
Thanks for putting the work into this @cjmlgrto 😄 , I think Mike's idea is good that we can remove this and close it down. All the information is accessible elsewhere and studies up this screen a bit if we remove it 👍

**Pull request closed without merging**
