### PR TITLE
Bugfix/android-disclaimer-exit

### PR DESCRIPTION
**Pull request by joshcase**
☝️ Fixed back button side-stepping disclaimer on Android

You can no longer close the disclaimer dialog without accepting on Android by pressing the back button.

## Changes

- Wrapped the Scaffold for the FutureBuilder in a WillPopScope on :109
- Disclaimer dialog now calls pushReplacementNamed instead of pushReplacement

## Screenshots

N/A

## Things to note

I did NOT provide testing as promised as I couldn't find a way to reliably simulate Android back button in either widget or integration testing - I encourage someone more experienced to do this if necessary/able.

### CODE REVIEW

**Review by workerbee22 — APPROVED** [review]
LGTM.

Although note once we do this. I'll work on a PR to remove the need for MediaQuery which still causes overflow runtime error on some devices.

**Comment by joshcase** [comment]
> Although note once we do this. I'll work on a PR to remove the need for MediaQuery which still causes overflow runtime error on some devices.
 
Thank you, I was getting the overflow error on my HTC One and meant to raise another issue but forgot.

**Comment by workerbee22** [comment]
Go for it @joshcase and we can at least fix this bug and thanks for fixing the Back button going from Home screen back to the Disclaimer. 👍

**Comment by workerbee22** [comment]
@joshcase have you run the PR-workflow and merged it?

**Comment by joshcase** [comment]
I don't have publish rights, someone else will have to merge! I'm also not that experienced working with large groups on GitHub, so if I've done something wrong feel free to point me in the right direction

**Comment by lukesleeman** [comment]
> I don't have publish rights, someone else will have to merge! I'm also not that experienced working with large groups on GitHub, so if I've done something wrong feel free to point me in the right direction

Hey @joshcase - your doing great 🙌!

It looks like there is a merge conflict that you will have to resolve - somebody else has changed one of the files you have.  There are a number of ways you can sort it out, but probably the easiest is just to click the "Resolve conflicts" button in this PR:

image

☝️ 

If you can't see the button, let me know and I'll walk you through what needs doing.

**Comment by lukesleeman** [comment]
Great work being so responsive  @joshcase ! I checked out what is going on and it seems that the build is failing due to the following issue:
```
  info • The value of the field '_agreedText' isn't used • lib/view/disclaimer_view.dart:27:9 • unused_field
```

Once you fix this up I can merge you changes into the app :-)

**Comment by joshcase** [comment]
Hope that last commit has sorted it. 

> Great work being so responsive @joshcase !

I'm mostly doing this because I know exactly how scary this is going to get when we have our knee surgeons operating ventilators - this app is going to be very, very useful :)

**Comment by lukesleeman** [comment]
🙌 Its all in!

**Comment by workerbee22** [comment]
@joshcase Don't worry ... as Flutter devs we are all learning how to do this in bigger teams, because we have up until now mainly worked alone. Looks good now, no conflicts etc. I'll push the 'Merge pull request' button. 

Going forward, the process as outlined by @maks is:

1. **New Branch** - make new branch off master, eg : adding-new-FB-dist-support, and commit your changes to THAT branch
2. **Push** - push that branch up to github
3. **Create PR** - create a new PR from that branch onto master
4. **PR Review by Others** - someone else reviews and ok PR and comments/approves the PR
5. **PR Merged** - PR merged to master which is automated now
6. **Check PR workflow Build** - Check it completed successfully, if not fix issues and recommit to THAT branch. 
7. **Master Build and Release** - Once approved and merged and successful PR-workflow build, gets a Master workflow build and released to Firebase App Distribution for Android. Message me to get on the distribution list for this. We also have iOS, message me your iPhone UDID to get these via FB as well.

@maks TWeaks to above process?

**Pull request merged**
