### PR TITLE
Adding pedantic to the mix

### PR DESCRIPTION
**Pull request by domesticmouse**

### CODE REVIEW

**Review by maks — APPROVED** [review]
👍

**Comment by lukesleeman** [comment]
@maks should we merge this now?  Or is it going to break anything @alessandrofavero has over in https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/pull/3

**Comment by maks** [comment]
Yes this should merged in. It may break things in other branch but that's better to fix now instead of later

**Comment by lukesleeman** [comment]
Ok, merging

**Pull request merged**
