### PR TITLE
Add checkbox SVGs.

### PR DESCRIPTION
**Pull request by marcedwards**
Added checkbox SVGs, needed for the checklist screens. We don’t currently have a down state for these. Maybe we can use opacity for that, or use a tint colour?

These SVGs are 30×30pt and have a little padding so they match the icon SVGs, and to increase the hit target area, making them easier to tap.

### Screenshot

scheckbox

### CODE REVIEW

**Comment by lukesleeman** [comment]
👋 Thanks for this @marcedwards !  With your PR do you mind if I re-write the commit comment to include `[skip ci]` to save us some build box minutes?  It will involve me force pushing to your branch

**Comment by ericjiang97** [comment]
@marcedwards Can you just add the checkmark  as an SVG? 

that way we can retain the checkbox functionality within the Flutter component.

**Comment by marcedwards** [comment]
@ericjiang97 I’m not exactly sure what you’re after? More info, please!

Edit: Oh, you just want the tick on its own? I can do that.

**Comment by ericjiang97** [comment]
> @ericjiang97 I’m not exactly sure what you’re after? More info, please!
> 
> Edit: Oh, you just want the tick on its own? I can do that.

Yep just the tick!

**Comment by ericjiang97** [comment]
Also need to update from master!

**Review by ericjiang97 — APPROVED** [review]

**Pull request merged**
