### PR TITLE
Make margins on home screen consistent

### LINKED ISSUE #314: Inconsistent gaps and margins on Home Screen
On our home screen, some of the gaps are inconsitent.
- Horizontal gaps in ICU and Resources sections are bigger than the Airway section.
- For ICU section, its head title is not lined up with its cards.

Simulator Screen Shot - iPhone 11 Pro - 2020-05-02 at 22 48 16

### PR DESCRIPTION
**Pull request by yimingc2**
Resolved #314

## Abstract
This PR will fix the inconsistent gaps on home screen. This issue is because the incorrect way of setting the default value in `ReusableCard.fromData`. If you don't specify the margin in its constructor, it will pass `null` to the card.

## Changes

- Add default values for height and margin in the constructor of `ReusableCard.fromData`

## Screenshots

Simulator Screen Shot - iPhone 11 Pro - 2020-05-02 at 23 01 51

### CODE REVIEW

**Review by lukesleeman — APPROVED** [review]
I have no idea on the kotlin side of things, however I checked the branch out and ran it side to side with master - looks good!  Great job on improving consistency!

**Comment by workerbee22** [comment]
@yimingc2 As per last night meeting, I assume this is still a WIP (Work In Progress) as you are looking at why the green cards are not as tall as the blue or white cards? So I'll rename to add [WIP] to the name.

**Comment by yimingc2** [comment]
Hey guys, I change the height of all cards in home screen to be consistent as 108dp.

**Review by workerbee22 — APPROVED** [review]
LGTM

**Comment by sallychung** [comment]
✅ 1.0.173

**Pull request merged**
