### PR TITLE
Backout Firebase Crashlytics

### PR DESCRIPTION
**Pull request by workerbee22**
## Abstract

- Backing out Firebase Crashlytics as could not get it working correctly. Not likely to be resolvable sort term due to Flutter package not supporting new Crashlytics SDK currently being rolled out. 
- Crashlytics backout in preparation to move to Sentry for crash & error reporting instead.
- Retain setup for Firebase connectivity for Firebase and Analytics generally.

## Changes

- Remove Crashlytics functions and classes
- Remove platform specific Crashlytics setup for iOS and Android
- Remove firebase_crashlytics package from pubspec and associated imports.

## Screenshots

- No UI changes
- No release notes updates

## Things to note

- Retested on iOS and Android to ensure no errors or issues
- Retained `WidgetsFlutterBinding.ensureInitialized()` in `main.dart` as is good practice for future changes for post Flutter v1.12.x projects.

### CODE REVIEW

**Comment by workerbee22** [comment]
@maks if you are OK with this then we can start Sentry implementation.

**Review by maks — CHANGES_REQUESTED** [review]
Did you mean to delete the `pubspec.lock` file?

**Comment by workerbee22** [comment]
> Did you mean to delete the `pubspec.lock` file?

@maks Yes I did because I didn't want the crashlytics package to still be in there even though i removed from pubspec.yaml.

Oops, but I didn't re-add the updated one. Adding it and doing another commit now 👍

**Comment by workerbee22** [comment]
See what happens when you change your IDE theme colors .... I don't recognise the file name colors anymore 🤣

**Review by maks — APPROVED** [review]
:+1:

**Pull request merged**
