### PR TITLE
Update to latest beta

### PR DESCRIPTION
**Pull request by domesticmouse**
Update the minimum flutter value to 1.17.0 in line with the latest beta release.

### CODE REVIEW

**Comment by lukesleeman** [comment]
We discussed this during tonights zoom call - given we are trying to get a beta build out to the hospital at the moment, we are going to hold off on the upgrade until after the long weekend.

**Comment by domesticmouse** [comment]
All good, this was meant to meant to be a guide for @workerbee22 on how to synchronise the upgrade. No intention to force anyone's hand here =)

**Comment by domesticmouse** [comment]
Hey @workerbee22, is this PR useful to y'all, or should I just close it out?

**Comment by workerbee22** [comment]
@domesticmouse Yep definitely still useful, we've just had and still have some higher priorities atm.

**Comment by workerbee22** [comment]
So I'm not aware of anything urgent we need in v1.17.0 for atm and given we are with 50+ now Beta testers, this is optional and not urgent atm.

@sallychung Your probably best placed to do a though test of the app across iOS and Android on the new version of Flutter. Lets chat about when we can do a thorough test on the new Beta channel of flutter v1.17.0.

@maks We might want to do a quick look at our packages to see if there are any obvious documented issues with going from v1.15.17 to v1.17 and do a check on any crashes so far.

If all that looks good, we can move the Dev team and update CI.

**Comment by workerbee22** [comment]
@domesticmouse Yes we should update the packages with this and any transitive dependencies. Also note we are on cocopods 1.9.1, a previous commit downgraded to 1.8.4 so just lookout for that on your local.

**Comment by workerbee22** [comment]
Also keeping an eye on issues flagged with v1.17 with the new tags that have started to be used in the flutter repo:

[flutter issues tagged as found in 1.17](https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22found+in+release%3A+1.17%22+sort%3Acomments-desc)

**Comment by workerbee22** [comment]
So looking at the list of issues with flutter v1.17 (currently is 1.17.0-dev.3.1) atm (see link above sorted by most comments) the key concerning one for us is this:

https://github.com/flutter/flutter/issues/52077

So quite happy at this stage to proceed carefully and only after a thorough test of the app on any new Flutter versions.

**Comment by domesticmouse** [comment]
I'm curious to see if this PR lands before or after 1.17 becomes stable ;-)

**Comment by workerbee22** [comment]
Morning Brett, we're still flat out dealing with other issues I'm afraid.
Beta 2 about to go out and we'll look at it again after that. But don't
think Sally or anyone has had a chance to test it yet.

Is there something specific you need it for?

Mike

**Comment by domesticmouse** [comment]
I’m quite happy to close this PR, and let y’all upgrade to the upcoming stable release on your own timeframe

**Comment by workerbee22** [comment]
@domesticmouse That might be a better plan for right now if its optional. We have bigger issues atm I'm afraid.

**Pull request closed without merging**
