### PR TITLE
Add a point to disclaimer about gathering analytics

### PR DESCRIPTION
**Pull request by lukesleeman**
This Pr adds a single point to the disclaimer about analytics and crash reporting

## Changes

Under the "Please keep in mind section" I've added
> WHAC19 gathers analytics and crash data which is used to improve the app.

The disclaimer version has been bumped to 4

## Screenshots

image

## Things to note

Nobody has agreed on this text!  This PR is just a bit of a straw-man for us to beat up on and hopefully improve!

### CODE REVIEW

**Review by sallychung — APPROVED** [review]
Better than nothing for now. Can we please create an issue to work on this copy for a future build?

**Comment by lukesleeman** [comment]
I've created an issue to track future changes to the app for a more permanent solution:

https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/241

**Review by maks — APPROVED** [review]

**Comment by lukesleeman** [comment]
Well ... I've got two ticks, so I guess I will merge :-)

**Comment by sallychung** [comment]
✅ v1.0.131
IMG_7D897357074E-1

**Pull request merged**
