### PR TITLE
Adding tuneup

### PR DESCRIPTION
**Pull request by domesticmouse**
@maks here's ya `tuneup` PR.

To use it in your CI/CD pipeline, run as follows:

```
$ flutter pub run tuneup
Checking project wh_covid19...
No issues found; analyzed 41 source files in 2.1s.
```

If you are encouraging people to format their code in a README, encourage people to also run this command alongside it. =)

### CODE REVIEW

**Comment by maks** [comment]
:+1: thats excellent! 
If you don't mind, I'll wait for #132 to be merged so then we can add with this PR to the Readme under `contributing` section to add this command.

**Comment by domesticmouse** [comment]
@maks I'll wait until you want me to land. =)

**Comment by workerbee22** [comment]
@maks I'll let you finish this one? 

Doco for this package is here: https://pub.dev/packages/tuneup

**Comment by workerbee22** [comment]
PR workflow build finished fine.

**Comment by maks** [comment]
@domesticmouse ok #132 is in now so if you could just add some doc in the Readme on using Tuneup we can get this merged or let me know if you want me to have a go at it

**Comment by domesticmouse** [comment]
@maks go for it =)

**Comment by maks** [comment]
After discussing with @domesticmouse on slack, going to close this as Codemagics built-in test & analyze workflow task already gives us mostly same functionality.

**Comment by domesticmouse** [comment]
Thanks @maks =)

**Pull request closed without merging**
