### PR TITLE
Flutter format, sort_child_properties_last

### PR DESCRIPTION
**Pull request by domesticmouse**
This is a tidyup PR.

## Changes

 - Run `flutter format .` 
 - Add in a few missing commas for consistent layout
 - Add `sort_child_properties_last` lint for consistent code
 - Reformat an oddly placed comment.

### CODE REVIEW

**Comment by joshcase** [comment]
LGTM - didn't know ```flutter format .``` existed - the more you know - thank you.

**Review by maks — APPROVED** [review]
:+1: :100:  Thanks @domesticmouse ! I think also someone is improving Readme at the moment and will include instructions for contributors to run `format` and use trailing commas.

**Comment by domesticmouse** [comment]
@maks if you want to enforce code formatting in you pre-submit checks, the following command will error out if the code needs re-formatting:

```bash
$ flutter format --dry-run --set-exit-if-changed .
```

Another worthwhile thing to add to your pre-submit checks is [`package:tuneup`](https://pub.dev/packages/tuneup) which will fail if there are failing lints. I'm happy to do a PR to add the package dep, and then we can chat about how to use it, if this is interesting.

**Comment by maks** [comment]
@domesticmouse 💯 please do a PR! 🙂

**Pull request merged**
