### PR TITLE
Bugfix/intubation copy changes

### PR DESCRIPTION
**Pull request by joshcase**
☝️ Copy changes as per #213, #214 

- [x] `release-notes.txt` has been updated.

## Changes

- Minor text changes

## Screenshots

Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-09 at 07 19 03
Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-09 at 07 17 21
Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-09 at 07 17 18
Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-09 at 07 17 15
Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-09 at 07 17 03
Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-09 at 07 16 44

## Things to note

@greggmiller I saw in the Intubation Checklist - Final tab we had a check box for "ECTO2 trace". I was 99% sure this was intended to be etCO2 trace (to be consistent with the rest of the app) so I went ahead and corrected it. Please verify before merging the PR!

### CODE REVIEW

**Comment by joshcase** [comment]
If these get merged, could someone with label privileges please add Design to #213 and #214 to enable @Mattro or similar to update Zeplin (with thanks).

**Review by workerbee22 — APPROVED** [review]
LGTM

**Comment by workerbee22** [comment]
@joshcase added Design tag to 213 and 214.

**Review by workerbee22 — APPROVED** [review]
LGTM

**Pull request merged**
