### PR TITLE
Updated logo with subtitle

### PR DESCRIPTION
**Pull request by marcedwards**
The logo SVG now has “ANAESTHESIA COVID-19” under it. Please note that the old SVG was `200×24pt`. The new SVG is `200×42pt`.

## Screenshot

logo

### CODE REVIEW

**Comment by rockgecko-development** [comment]
Looks extremely small Marc 
image

**Comment by rockgecko-development** [comment]
If you edit this line in `home_page` from 24 to 42 then it's good to go:
https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/blob/0d2ceef3a56afa4d0ca1ce6af069ea2bc42987c2/lib/view/home_page.dart#L62

image

**Review by rockgecko-development — CHANGES_REQUESTED** [review]
If you edit this line in home_page from `24` to `42` then it's good to go:
https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/blob/0d2ceef3a56afa4d0ca1ce6af069ea2bc42987c2/lib/view/home_page.dart#L62

**Comment by lukesleeman** [comment]
@rockgecko-development great catch!  Do you want to make the change to that file as part of this branch, then we can merge it?

**Review by rockgecko-development — APPROVED** [review]

**Pull request merged**
