### PR TITLE
[skip ci] Add information on using git with https

### PR DESCRIPTION
**Pull request by sallychung**
New “troubleshoot" section under `doc/GitHub101.md` including information on how to solve 403 issues when trying to push via https

### CODE REVIEW

**Review by lukesleeman — APPROVED** [review]
👍 It looks very good @sallychung - thanks for getting onto this.

Before you merge, is it possible to re-write your commit titles to include [skip ci] - seems that we are burning through the CI minutes at the moment 😬

**Comment by sallychung** [comment]
@lukesleeman rewrite every single commit message I’ve pushed?

**Comment by lukesleeman** [comment]
> @lukesleeman rewrite every single commit message I’ve pushed?

If possible?  Its not a biggie if you cant re-write, but unfortunately the CI will run and build the app even for documentation changes.  We have been burning through CI minutes at quite the alarming rate.  If your commit messages include `[skip ci]` in the title the CI will ignore that particular commit.

If its going to be troublesome, or you don't have the time at the moment - thats fine, we can just merge this one as is :-)

**Comment by lukesleeman** [comment]
Oh, 😅 - I should have mentioned I also have tower, which makes it pretty easy - you just right click and go "edit commit message" followed by a force push.  If it would be easier for you I could make the changes ... I just don't want to be force pushing into anybodies branch 😬

**Comment by sallychung** [comment]
There’s been quite a few merges before my commit so I’d rather not mess around rewriting. I’ll just merge this one and remember to skip ci if they’re doc changes.

**Comment by lukesleeman** [comment]
🎉 Great work 👍

**Pull request merged**
