### PR TITLE
Adds new iOS and Android adpative icon.

### PR DESCRIPTION
**Pull request by marcedwards**
This adds the icon PNGs for iOS and Android adaptive icons (standard Android icons are still to come). Please note that I have not created iOS sizes for 57 and 114. I’m not sure if those sizes are used?

## Screenshots

App Icon - Apple iOS

## Things to note

The adaptive icons will need to be tested on device — the icon may be a little too big once masked.

### CODE REVIEW

**Comment by workerbee22** [comment]
@marcedwards re those questions:

- Android adaptive icon wise, we'll tweak using AndroidStudio if necessary, as it also shows all the standard adaptive shapes. So will flag if any of them look 'not quite right' before we change anything.

- iOS we'll need all the sizes including iOS sizes for 57 and 114. These iPad resolutions are now required by Apple and no longer optional. We had to fix the previous set, so now we absolutely need all of these:

image

**Comment by marcedwards** [comment]
That’s strange. Xcode doesn’t need them, and they’re not mentioned in Apple’s icon docs. I think those sizes are old and no longer used. If my memory serves me, 57px was the pre-iOS 7 iPhone home screen icon size (and 114px is the Retina version of that).

https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/

app-icon-sizes

**Comment by workerbee22** [comment]
@marcedwards What Xcode version are you using? You should see these warnings in Xcode (just warnings I thought too ... no big deal):

image

But when you try to upload to App Store Connect they are errors and the upload FAILS:

image

**Comment by marcedwards** [comment]
76 × 2 is 152px. We have that size. 83.5 × 2 is 167px. We have that one as well. 😀

**Comment by workerbee22** [comment]
Its part of the 'new' but slightly delayed requirements here: https://developer.apple.com/news/?id=03262020b

But App Store Connect is already enforcing these two:

image

Flutter already does Launch screen correctly, but we also need all the iPad icon resolutions too.

**Comment by marcedwards** [comment]
There must be some confusion. 57px and 114px icons are pre-iOS 7 sizes. They’re not used in any modern version of iOS, as far as I know. That was the original 2007 iPhone app icon size!

**Comment by marcedwards** [comment]
I can make the files up, it’s just very strange there’s a warning!

**Comment by workerbee22** [comment]
So just to be clear looks like we just need those extra of 76x76, 167x167 and 152x152. So in Xcode for the project atm we have:

image

**Comment by workerbee22** [comment]
But its Apple ... so its their way or no way. 🤷‍♂️

**Comment by marcedwards** [comment]
Here’s what I provided. 76×76, 167×167 and 152×152 are there.

- 1024.png
- 180.png
- 167.png
- 152.png
- 120.png
- 87.png
- 80.png
- 76.png
- 60.png
- 58.png
- 40.png
- 29.png
- 20.png

Are we targeting iOS 6?!

**Comment by workerbee22** [comment]
Cool looks good 👍If there are any App Store Connect issues I'll let you know 👍

**Review by workerbee22 — APPROVED** [review]
LGTM 👍

**Comment by workerbee22** [comment]
Just checking on devices and have some issues ...

**Pull request merged**
