### PR TITLE
Multiple Copy changes in Intubation guide

### PR DESCRIPTION
**Pull request by greggmiller**
Simulator Screen Shot - iPhone 11 Pro Max - 2020-05-01 at 12 16 06
Simulator Screen Shot - iPhone 11 Pro Max - 2020-05-01 at 12 16 03

Major copy changes to reflect mos recent guidelines.
Removal of multiple emojis and replaced with bullet points. This leaves some section quite lifeless compared to before so I am open to suggestions on this.

☝️ Provide a short & descriptive title for this PR.

Provide a more detailed summary of the changes in this PR here.  What does it do?

- [ ] `release-notes.txt` has been updated.
(👆 delete this line if your changes have no user facing features)

## Changes

- Dot points explaining what is changed
- Did the thing
- Changed some stuff

## Screenshots

If your PR changes anything visual please paste in some screenshots of the app here.  Make sure you are working off the designs in zeplin.  If your PR makes some significant visual tweaks feel free to include one of the designers as a reviewer, so they can check off and comment on what is changing.

## Things to note

Include anything else the other Devs or Designers on the project should know?  Will there be work you are deferring now, which done in later follow up PRs?   Does this change anything about the code base they need to be aware of?

### CODE REVIEW

**Comment by workerbee22** [comment]
@greggmiller yeah I have to say bullets with bullets doesn't look great. Is this temporary ? Because I thought you were going to pick new emojis based on @sallychung list of good emojis to use?

**Comment by greggmiller** [comment]
Yeah I’m happy for emojis and to amend 👍 I just didn’t have time today. I only had an hour window.

**Comment by workerbee22** [comment]
👍

**Comment by workerbee22** [comment]
> Yeah I’m happy for emojis and to amend 👍 I just didn’t have time today. I only had an hour window.

@greggmiller Then we won't merge this PR yet, until you get a chance to change the bullets to one of the 'safe' emojis from @sallychung

**Comment by lukesleeman** [comment]
Actually, I was going to try my hand at picking some emoji.  I would suggest the following:

1. Merge this PR - the bullets are at least an improvement to the ✅ if we don't manage to get anything else in.
2. I'll create a new PR with some suggested emoji
3. Greg can review my PR and make suggestions, etc based on that.

What do we think?

**Review by workerbee22 — APPROVED** [review]
LGTM .... Luke will come in after this PR and replace the bullets with new emojis.

**Pull request merged**
