### PR TITLE
Added the donning and doffing PPE images for each step

### PR DESCRIPTION
**Pull request by marcedwards**
This should be the complete and maybe even final set of images for all the donning and doffing PPE steps. Images prefixed with `on_` are the steps for putting _ON_ PPe. Images prefixed with `off_` are for _REMOVING_ PPE.

## Screenshots

PPE

## Things to note

- The intention is for these images to simply scale with the device size. We don’t need 1×, 2× etc pixel density images for them.
- If these files end up being too big, we could use JPEG or indexed PNGs.
- Are the images in a good location? I’ll let the devs on the team decide.

### CODE REVIEW

**Comment by lukesleeman** [comment]
OMG marc, this is increadible how didi you do it!  ❤️

**Comment by marcedwards** [comment]
We have Matt and Gregg to thank for the high quality images! Onto the next one…

**Review by maks — APPROVED** [review]
@marcedwards :tada: :+1: 

if you could just add the path `- assets/images/steps/`to `pubspec.yaml` file underneath the   existing lines, eg. `- assets/images/icon/` that woudl be fab but no biggie if not as first dev who goes to use these assets can do that too.

**Comment by marcedwards** [comment]
@maks If it’s okay, I may leave that to someone more capable?

**Comment by maks** [comment]
no worries at all @marcedwards thanks again! You're good to merge this now :+1:

**Pull request merged**
