### PR TITLE
[Fix] Emoji Alignment and Bottom Cut Off

### LINKED ISSUE #281: Emoji’s cut off on the bottom
Emoji’s on the bottom are cut off for some screens. 
Looks like it only happens to the last item of the first section if the text doesn’t wrap multiple lines.

Note: Separate issue raised on emoji alignment #282

Affected:
- [ ] **A** Your welfare/The basics 🗞 Limit new Intake
- [ ] **B** Your welfare//Pre-phase 🔥 "Readiness" burnout
- [ ] **C** Your welfare//Core pahse 😵 Distress
- [ ] **D** Your welfare/End phase 😖 Post-traumatic stress
- [ ] **E** Your welfare/Long term 😖 Post-traumatic stress
- [ ] **F** Cross Skilling/Proning/Staff Pre-Manoeuvre 😮 Able to reintubate?
- [ ] **G** Cross Skilling/ALS/BLS/PPE ☣️ Full PPE

Copy changes 008

Copy changes 009

### LINKED ISSUE #282: Emoji alignments in Your Welfare and Cross Skilling
Emojis for each cell is not aligned with it’s text.
This affects all screens across You Welfare, Proning and ALS/BLS

Image highlights a few screens that stands out the most.

There’s also a vertical alignment under Proning. ６6 x staff available for proning

Copy changes 010

### PR DESCRIPTION
**Pull request by yimingc2**
Resloved #281 #282

## Abstract
This PR will fix the issue of improper alignment and bottom cut off the emojis. There might be some bug when flutter renders the emoji object. So for now, I just simply increase the title font size so that the container's height is good enough for displaying the whole emoji.

## Changes

- Use larger font size for the title

## Screenshots
Simulator Screen Shot - iPhone 11 Pro - 2020-04-26 at 14 14 46

### CODE REVIEW

**Review by kimngyn — APPROVED** [review]
Lgtm

**Comment by workerbee22** [comment]
Had a closer look, I have a more comprehensive fix for #281 #282 but this seems to work too? 

So LGTM.

**Comment by yimingc2** [comment]
> Had a closer look, I have a more comprehensive fix for #281 #282 but this seems to work too?
> 
> So LGTM.

Thanks for your help @workerbee22 , giving them weight to prioritize available space is good!

**Comment by workerbee22** [comment]
New commit to fix both alignment and emoji being cut off.

There is a few things in there they give us more flexibility .... but yes the padding around text was key, but it works with the Columns and Expanded :+1:
Should now be easier to tweak those Padding widgets too to get it just right.

**Comment by kimngyn** [comment]
Nice!

**Comment by workerbee22** [comment]
@sallychung We have this 100% emoji cut-off and I think 90% emoji alignment resolved. 

Can you please check this branch, as may have to tweak alignment a bit.

**Review by workerbee22 — APPROVED** [review]
So we've tweaked the widegt quite a bit but LGTM.

**Pull request merged**
