### PR TITLE
restore pedantic pkg ver back to 1.9.0

### PR DESCRIPTION
**Pull request by maks**

### CODE REVIEW

**Review by workerbee22 — APPROVED** [review]
LGTM

**Comment by domesticmouse** [comment]
I'm curious if this made any difference to your pubspec.lock file, it should already have been at 1.9. If you really want to enforce pedantic 1.9, however, you need to change the version in the analysis file. Or use the non-versioned import.

**Comment by maks** [comment]
@domesticmouse I think this came about due to Flutter sdk pinning pedantic pkg and current stable pinning it to 1.8. I found more info about it here:  https://github.com/dart-lang/pedantic/issues/46#issuecomment-571359160

**Comment by domesticmouse** [comment]
Yeah, flutter hard pins version of `pedantic` somewhere. I couldn't remember what version of pedantic `stable` channel is currently running, I'm pretty much stuck on `dev` channel due to my desktop development work.

**Pull request merged**
